from __future__ import annotations

import json
from pathlib import Path
from typing import Any

DEFAULT_ACTION_SEQUENCE: list[tuple[str, str]] = [
    ("up", "Up"),
    ("down", "Down"),
    ("left", "Left"),
    ("right", "Right"),
    ("center", "OK / Select"),
    ("back", "Back"),
    ("home", "Home"),
    ("menu", "Menu"),
    ("volume_up", "Volume +"),
    ("volume_down", "Volume -"),
]

KNOWN_CODE_TEXT = {
    103: "KEY_UP",
    108: "KEY_DOWN",
    105: "KEY_LEFT",
    106: "KEY_RIGHT",
    353: "KEY_SELECT",
    158: "KEY_BACK",
    172: "KEY_HOMEPAGE",
    580: "KEY_MENU_OR_VENDOR",
    115: "KEY_VOLUMEUP",
    114: "KEY_VOLUMEDOWN",
    116: "KEY_POWER",
    582: "KEY_VENDOR_ASSISTANT",
}


def code_text(code: int) -> str:
    return KNOWN_CODE_TEXT.get(int(code), f"KEY_{int(code)}")


def build_keymap_from_codes(codes: dict[str, int], *, device: str = "Xiaomi / MiTV Bluetooth remote", mac: str = "") -> dict[str, Any]:
    keys: dict[str, dict[str, Any]] = {}
    for action, label in DEFAULT_ACTION_SEQUENCE:
        if action not in codes:
            continue
        code = int(codes[action])
        keys[action] = {
            "label": label,
            "code_text": code_text(code),
            "code": code,
            "event": "auto",
        }
    return {
        "device": device,
        "mac": mac or "AA:BB:CC:DD:EE:FF",
        "note": "Generated by xiaomi-mitv-remote-capture. Event paths are resolved at runtime; code fallback is the stable mapping.",
        "keys": keys,
    }


def write_keymap(path: Path, keymap: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(keymap, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


VALID_ACTIONS = {action for action, _label in DEFAULT_ACTION_SEQUENCE} | {"power", "mute", "play_pause", "voice", "assistant"}


def validate_keymap(data: dict) -> dict:
    if not isinstance(data, dict):
        raise ValueError("keymap must be a JSON object")
    keys = data.get("keys")
    if not isinstance(keys, dict) or not keys:
        raise ValueError("keymap.keys must be a non-empty object")
    seen_codes: dict[int, str] = {}
    warnings: list[str] = []
    for action, item in keys.items():
        if not isinstance(action, str) or not action:
            raise ValueError("keymap action names must be non-empty strings")
        if action not in VALID_ACTIONS:
            warnings.append(f"unknown action name: {action}")
        if not isinstance(item, dict):
            raise ValueError(f"keys.{action} must be an object")
        if "code" not in item:
            raise ValueError(f"keys.{action}.code is required")
        code = int(item["code"])
        if code < 0 or code > 4096:
            raise ValueError(f"keys.{action}.code is outside expected Linux EV_KEY range: {code}")
        if code in seen_codes:
            warnings.append(f"code {code} is mapped to both {seen_codes[code]} and {action}")
        seen_codes[code] = action
        if "event" in item and item["event"] not in (None, "auto") and not str(item["event"]).startswith("/dev/input/event"):
            warnings.append(f"keys.{action}.event is not /dev/input/eventN or auto: {item['event']}")
    recommended = {"up", "down", "left", "right", "center", "back"}
    missing = sorted(recommended - set(keys))
    if missing:
        warnings.append("missing recommended actions: " + ", ".join(missing))
    return {"actionCount": len(keys), "warnings": warnings, "actions": sorted(keys)}
