from __future__ import annotations

import json
from pathlib import Path
from typing import Any

DEFAULT_ACTION_SEQUENCE: list[tuple[str, str]] = [
    ("up", "Up"),
    ("down", "Down"),
    ("left", "Left"),
    ("right", "Right"),
    ("center", "OK / Select"),
    ("back", "Back"),
    ("home", "Home"),
    ("menu", "Menu"),
    ("volume_up", "Volume +"),
    ("volume_down", "Volume -"),
]

KNOWN_CODE_TEXT = {
    103: "KEY_UP",
    108: "KEY_DOWN",
    105: "KEY_LEFT",
    106: "KEY_RIGHT",
    353: "KEY_SELECT",
    158: "KEY_BACK",
    172: "KEY_HOMEPAGE",
    580: "KEY_MENU_OR_VENDOR",
    115: "KEY_VOLUMEUP",
    114: "KEY_VOLUMEDOWN",
    116: "KEY_POWER",
    582: "KEY_VENDOR_ASSISTANT",
}


def code_text(code: int) -> str:
    return KNOWN_CODE_TEXT.get(int(code), f"KEY_{int(code)}")


def build_keymap_from_codes(codes: dict[str, int], *, device: str = "Xiaomi / MiTV Bluetooth remote", mac: str = "") -> dict[str, Any]:
    keys: dict[str, dict[str, Any]] = {}
    for action, label in DEFAULT_ACTION_SEQUENCE:
        if action not in codes:
            continue
        code = int(codes[action])
        keys[action] = {
            "label": label,
            "code_text": code_text(code),
            "code": code,
            "event": "auto",
        }
    return {
        "device": device,
        "mac": mac or "AA:BB:CC:DD:EE:FF",
        "note": "Generated by xiaomi-mitv-remote-capture. Event paths are resolved at runtime; code fallback is the stable mapping.",
        "keys": keys,
    }


def write_keymap(path: Path, keymap: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(keymap, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
